In [1]:
import numpy as np

In [4]:
#NumPy Arrays

In [ ]:
#Array can be used for vectorised calculation

In [2]:
my_list = [1,2,3,4,5,6]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr2d = np.array(my_mat, dtype = 'float')

In [9]:
arr2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [11]:
pwd

'C:\\Users\\Mr.x'

In [13]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:
np.linspace(1,51,26)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(4)

array([0.29934107, 0.86714884, 0.17191771, 0.09707052])

In [26]:
np.random.rand(4,4)

array([[0.94024465, 0.09741624, 0.10905334, 0.28522022],
       [0.57538402, 0.45633493, 0.44227527, 0.598792  ],
       [0.33019711, 0.41387346, 0.1535939 , 0.60640553],
       [0.72716951, 0.46665143, 0.62001961, 0.11959468]])

In [27]:
np.random.randn(3)

array([-1.49532698, -0.21094996, -1.084576  ])

In [28]:
np.random.randint(0,25,5)

array([16, 12, 21, 17, 19])

In [30]:
arr = np.arange(25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr = np.random.randint(0,50,10)

In [33]:
ranarr

array([24, 34, 28,  6, 48, 35, 28, 32,  8,  3])

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
ranarr.max()

48

In [36]:
ranarr.min()

3

In [37]:
ranarr.argmax()

4

In [38]:
ranarr.argmin()

9

In [43]:
ranarr.shape

(10,)

In [44]:
arr.dtype

dtype('int32')

In [ ]:
#Indexing

In [45]:
arr = np.arange(0,11)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[5]

5

In [48]:
arr[:5]

array([0, 1, 2, 3, 4])

In [49]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [50]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [51]:
slice_of_arr = arr[0:6]

In [53]:
slice_of_arr[:] = 100

In [54]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [ ]:
#Make a copy to make sure it doesn't change the original list array

In [55]:
arr_copy = arr.copy()

In [56]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [57]:
arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [58]:
arr_copy[:] = 100

In [59]:
arr_copy    

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [60]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [61]:
#Indexing and Selection

In [70]:
arr_2d = np.arange(50).reshape(5,10)

In [71]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [75]:
arr_2d[2:,1:7]

array([[21, 22, 23, 24, 25, 26],
       [31, 32, 33, 34, 35, 36],
       [41, 42, 43, 44, 45, 46]])

In [77]:
arr_2d[1:4,:7]

array([[10, 11, 12, 13, 14, 15, 16],
       [20, 21, 22, 23, 24, 25, 26],
       [30, 31, 32, 33, 34, 35, 36]])

In [1]:
#NumPy Operation
#Array with array

In [8]:
import numpy as np

In [9]:
arr = np.arange(11)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [10]:
arr / arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
1 / arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [12]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [14]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [15]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [16]:
np.max(arr)

10

In [17]:
np.log(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [12]:
arr2d = np.array(arr)

In [12]:
arr2d[0][0] = np.nan
arr2d

array([[nan,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [13]:
arr2d[0][1] = np.inf
arr2d

array([[nan, inf,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [17]:
np.isnan(arr2d)

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [18]:
np.isinf(arr2d)

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [23]:
missing_num = np.isnan(arr2d) | np.isinf(arr2d)
missing_num

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [24]:
arr2d[missing_num] = 0

In [14]:
arr = [[1,2,3],[4,5,6],[7,8,9]]

In [15]:
arr

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
arr2d = np.array(arr)

In [17]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr2d[1:2, 1:2]

array([[5]])

In [20]:
arr2d.reshape(3,4)

ValueError: cannot reshape array of size 9 into shape (3,4)

In [21]:
arr2d.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [22]:
arr2d.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [23]:
arr2d.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr2d.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [27]:
np.arange(2,50,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [28]:
np.linspace(1,50,25)

array([ 1.        ,  3.04166667,  5.08333333,  7.125     ,  9.16666667,
       11.20833333, 13.25      , 15.29166667, 17.33333333, 19.375     ,
       21.41666667, 23.45833333, 25.5       , 27.54166667, 29.58333333,
       31.625     , 33.66666667, 35.70833333, 37.75      , 39.79166667,
       41.83333333, 43.875     , 45.91666667, 47.95833333, 50.        ])

In [29]:
np.logspace(1,50,1)

array([10.])

In [31]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
a = [1,2,3]

In [35]:
np.tile(a, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [36]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [37]:
np.random.rand(3,3)

array([[0.10776205, 0.96850258, 0.70134933],
       [0.08399295, 0.60371424, 0.77768331],
       [0.323907  , 0.6011631 , 0.45392346]])

In [38]:
np.random.seed(0)

In [40]:
np.random.randint(1,10,[2,5])

array([[6, 1, 4, 4, 8],
       [4, 6, 3, 5, 8]])